name: argus
description: Geo-fence monitoring app per spec.md
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^10.1.0
  file_selector: ^1.0.1
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  logger: ^2.0.2
  collection: ^1.17.2
  meta: ^1.10.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/config/default_config.json
    - assets/geojson/
